const Pieces = [
    {
        name: 'WhiteRookL',
        type: 'rook',
        fa: 'fa-regular fa-chess-rook fa-3x',
        player: 'white',
        selected: false,
        possibleMove: false,
        startingPosition: 0,
    },
    {
        name: 'WhiteKnightL',
        type: 'knight',
        fa: 'fa-regular fa-chess-knight fa-3x',
        player: 'white',
        selected: false,
        possibleMove: false,
        startingPosition: 1,
    },
    {
        name: 'WhiteBishopL',
        type: 'bishop',
        fa: 'fa-regular fa-chess-bishop fa-3x',
        player: 'white',
        selected: false,
        possibleMove: false,
        startingPosition: 2,
    },
    {
        name: 'WhiteKing',
        type: 'king',
        fa: 'fa-regular fa-chess-king fa-3x',
        player: 'white',
        selected: false,
        possibleMove: false,
        startingPosition: 3,
    },
    {
        name: 'WhiteQueen',
        type: 'queen',
        fa: 'fa-regular fa-chess-queen fa-3x',
        player: 'white',
        selected: false,
        possibleMove: false,
        startingPosition: 34,
    },
    {
        name: 'WhiteBishopR',
        type: 'bishop',
        fa: 'fa-regular fa-chess-bishop fa-3x',
        player: 'white',
        selected: false,
        possibleMove: false,
        startingPosition: 5,
    },
    {
        name: 'WhiteKnightR',
        type: 'knight',
        fa: 'fa-regular fa-chess-knight fa-3x',
        player: 'white',
        selected: false,
        possibleMove: false,
        startingPosition: 6,
    },
    {
        name: 'WhiteRookR',
        type: 'rook',
        fa: 'fa-regular fa-chess-rook fa-3x',
        player: 'white',
        selected: false,
        possibleMove: false,
        startingPosition: 7,
    },
    {
        name: 'WhitePawn1',
        type: 'pawn',
        fa: 'fa-regular fa-chess-pawn fa-3x',
        player: 'white',
        selected: false,
        possibleMove: false,
        startingPosition: 8,
    },
    {
        name: 'WhitePawn2',
        type: 'pawn',
        fa: 'fa-regular fa-chess-pawn fa-3x',
        player: 'white',
        selected: false,
        possibleMove: false,
        startingPosition: 9,
    },
    {
        name: 'WhitePawn3',
        type: 'pawn',
        fa: 'fa-regular fa-chess-pawn fa-3x',
        player: 'white',
        selected: false,
        possibleMove: false,
        startingPosition: 10,
    },
    {
        name: 'WhitePawn4',
        type: 'pawn',
        fa: 'fa-regular fa-chess-pawn fa-3x',
        player: 'white',
        selected: false,
        possibleMove: false,
        startingPosition: 11,
    },
    {
        name: 'WhitePawn5',
        type: 'pawn',
        fa: 'fa-regular fa-chess-pawn fa-3x',
        player: 'white',
        selected: false,
        possibleMove: false,
        startingPosition: 12,
    },
    {
        name: 'WhitePawn6',
        type: 'pawn',
        fa: 'fa-regular fa-chess-pawn fa-3x',
        player: 'white',
        selected: false,
        possibleMove: false,
        startingPosition: 13,
    },
    {
        name: 'WhitePawn7',
        type: 'pawn',
        fa: 'fa-regular fa-chess-pawn fa-3x',
        player: 'white',
        selected: false,
        possibleMove: false,
        startingPosition: 14,
    },
    {
        name: 'WhitePawn8',
        type: 'pawn',
        fa: 'fa-regular fa-chess-pawn fa-3x',
        player: 'white',
        selected: false,
        possibleMove: false,
        startingPosition: 15,
    },
    {
        name: 'BlackPawn1',
        type: 'pawn',
        fa: 'fa-regular fa-chess-pawn fa-3x',
        player: 'black',
        selected: false,
        possibleMove: false,
        startingPosition: 48,
    },
   {
        name: 'BlackPawn2',
        type: 'pawn',
        fa: 'fa-regular fa-chess-pawn fa-3x',
        player: 'black',
        selected: false,
        possibleMove: false,
        startingPosition: 49,
    },
    {
        name: 'BlackPawn3',
        type: 'pawn',
        fa: 'fa-regular fa-chess-pawn fa-3x',
        player: 'black',
        selected: false,
        possibleMove: false,
        startingPosition: 50,
    },
    {
        name: 'BlackPawn4',
        type: 'pawn',
        fa: 'fa-regular fa-chess-pawn fa-3x',
        player: 'black',
        selected: false,
        possibleMove: false,
        startingPosition: 51,
    },
    {
        name: 'BlackPawn5',
        type: 'pawn',
        fa: 'fa-regular fa-chess-pawn fa-3x',
        player: 'black',
        selected: false,
        possibleMove: false,
        startingPosition: 52,
    },
    {
        name: 'BlackPawn6',
        type: 'pawn',
        fa: 'fa-regular fa-chess-pawn fa-3x',
        player: 'black',
        selected: false,
        possibleMove: false,
        startingPosition: 53,
    },
    {
        name: 'BlackPawn7',
        type: 'pawn',
        fa: 'fa-regular fa-chess-pawn fa-3x',
        player: 'black',
        selected: false,
        possibleMove: false,
        startingPosition: 54,
    },
    {
        name: 'BlackPawn8',
        type: 'pawn',
        fa: 'fa-regular fa-chess-pawn fa-3x',
        player: 'black',
        selected: false,
        possibleMove: false,
        startingPosition: 55,
    },
    {
        name: 'BlackRookL',
        type: 'rook',
        fa: 'fa-regular fa-chess-rook fa-3x',
        player: 'black',
        selected: false,
        possibleMove: false,
        startingPosition: 56,
    },
    {
        name: 'BlackKnightL',
        type: 'knight',
        fa: 'fa-regular fa-chess-knight fa-3x',
        player: 'black',
        selected: false,
        possibleMove: false,
        startingPosition: 57,
    },
    {
        name: 'BlackBishopL',
        type: 'bishop',
        fa: 'fa-regular fa-chess-bishop fa-3x',
        player: 'black',
        selected: false,
        possibleMove: false,
        startingPosition: 58,
    },
    {
        name: 'BlackKing',
        type: 'king',
        fa: 'fa-regular fa-chess-king fa-3x',
        player: 'black',
        selected: false,
        possibleMove: false,
        startingPosition: 59,
    },
    {
        name: 'BlackQueen',
        type: 'queen',
        fa: 'fa-regular fa-chess-queen fa-3x',
        player: 'black',
        selected: false,
        possibleMove: false,
        startingPosition: 60,
    },
    {
        name: 'BlackBishopR',
        type: 'bishop',
        fa: 'fa-regular fa-chess-bishop fa-3x',
        player: 'black',
        selected: false,
        possibleMove: false,
        startingPosition: 61,
    },
    {
        name: 'BlackKnightR',
        type: 'knight',
        fa: 'fa-regular fa-chess-knight fa-3x',
        player: 'black',
        selected: false,
        possibleMove: false,
        startingPosition: 62,
    },
    {
        name: 'BlackRookR',
        type: 'rook',
        fa: 'fa-regular fa-chess-rook fa-3x',
        player: 'black',
        selected: false,
        possibleMove: false,
        startingPosition: 63,
    },
]

export default Pieces